version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      production-minor:
        dependency-type: production
        update-types: [minor, patch]
    open-pull-requests-limit: 10
  - package-ecosystem: pub
    directory: /apps/mobile
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
